# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Turkana spellchecker"
tuv = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Turkana, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
tuv = "TRANSLATE: A spellchecker for Turkana, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.tuv"

[windows]
system_product_code = "{A9D7D1E8-4B23-4F0C-BF9B-49C5227AEA0E}_is1"
legacy_product_codes = [
    { value = "D482430A-8DE0-4156-A8AD-C6B79FDA1FBD", kind = "nsis" },
    { value = "25A5028E-E903-4370-83A3-2B6563B55E5B", kind = "nsis" }
]

[package.speller]
name = "Turkana"
version = "0.1.1"

[package.grammar]
name = "Turkana"
version = "0.1.0"

[package.tts-text-proc]
name = "Turkana"
version = "0.1.0"

[package.hyphenator]
name = "__UNDEFINED__"
version = "0.1.0"
