template = "https://github.com/giellalt/template-lang-und"
rev_id = 258
template_sha = "b5271fc37dc1cf0a7448e0553c24b3f857121d34"

[replacements]
__GLOTTOLOG_ID__ = "turk1308"
__REPO__ = "lang-tuv"
__UND2C__ = "tuv"
__UNDEFINED__ = "Turkana"
__UND__ = "tuv"
